name: Portfolio Page Build & Deploy
run-name: ${{ github.actor }} updated Portfolio Page
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '11'

      - name: Install
        run: |
          npm install
          npm run build
  
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.      
          clean: true
          clean-exclude:
            cname
            examples/*.*
