name: Portfolio Page Build & Deploy
run-name: ${{ github.actor }} updated Portfolio Page
on:
  push:
    branches:
      - prod
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '11'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Upload Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: build
          clean: false
          clean-exclude: |
            CNAME

  

