name: Portfolio Page Build & Deploy
run-name: ${{ github.actor }} updated Portfolio Page
on:
  push:
    branches:
      - prod
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '11'

      - name: Install
        run: |
          npm install
          npm run build
  

